spring.datasource.url=jdbc:postgresql://ep-wild-leaf-a2r788uo.eu-central-1.aws.neon.tech:5432/planmyrun?sslmode=require
spring.datasource.username=planmyrun_owner
spring.datasource.password=rI0xnPmFf5ob
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
